version: '2'
services:

  zookeeper:
    image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
    hostname: "zookeeper"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  mesos-master:
    image: datastrophic/mesos-master:0.28.1
    hostname: "mesos-master"
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-master
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
    links:
      - zookeeper
    ports:
      - "5050:5050"

  mesos-slave:
    image: datastrophic/mesos-slave-spark:mesos-0.28.1-spark-1.6
    hostname: "mesos-slave"
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - SPARK_PUBLIC_DNS=mesos-slave
      - CUSTOM_EXECUTOR_HOME=/throttle
    links:
      - zookeeper
      - mesos-master
      - cassandra
    ports:
      - "5151:5151"
      - "4040:4040"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
      - ./executor:/throttle

  marathon:
    image: datastrophic/marathon:0.15.3
    hostname: "marathon"
    environment:
      - MARATHON_HOSTNAME=marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/marathon
    links:
      - zookeeper
      - mesos-master
      - mesos-slave
    ports:
      - "8080:8080"

  cassandra:
    image: cassandra:3.3
    hostname: "cassandra"
    ports:
      - "9160:9160"
      - "9042:9042"