version: '2'
services:

  zookeeper:
    image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
    hostname: "zookeeper"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  mesos-master:
    image: mesoscloud/mesos-master:0.24.1-ubuntu-14.04
    hostname: "mesos-master"
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-master
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
    links:
      - zookeeper
    ports:
      - "5050:5050"

  mesos-slave-1:
    image: mesoscloud/mesos-slave:0.24.1-ubuntu-14.04
    hostname: "mesos-slave-1"
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave-1
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
    links:
      - zookeeper
      - mesos-master
    ports:
      - "5151:5151"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock

  mesos-slave-2:
    image: mesoscloud/mesos-slave:0.24.1-ubuntu-14.04
    hostname: "mesos-slave-2"
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave-2
      - MESOS_PORT=5252
      - MESOS_MASTER=zk://zookeeper:2181/mesos
    links:
      - zookeeper
      - mesos-master
    ports:
      - "5252:5252"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v0.15.3
    hostname: "marathon"
    environment:
      - MARATHON_HOSTNAME=marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/marathon
    links:
      - zookeeper
      - mesos-master
    ports:
      - "8080:8080"

  chronos:
    image: mesoscloud/chronos:2.4.0-ubuntu-14.04
    hostname: "chronos"
    environment:
      - CHRONOS_HTTP_PORT=4400
      - CHRONOS_MASTER=zk://zookeeper:2181/mesos
      - CHRONOS_ZK_HOSTS=zookeeper:2181
    links:
      - zookeeper
      - mesos-master
    ports:
      - "4400:4400"